# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatPrivado.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63hatPrivado.proto\" \n\x0cMisatgeRebut\x12\x10\n\x08missatge\x18\x01 \x01(\t\"!\n\rMisatgeEnviat\x12\x10\n\x08missatge\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2e\n\x04\x43hat\x12\x31\n\x0e\x45nviarMissatge\x12\x0e.MisatgeEnviat\x1a\r.MisatgeRebut\"\x00\x12*\n\rRebreMissatge\x12\x06.Empty\x1a\r.MisatgeRebut\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatPrivado_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MISATGEREBUT']._serialized_start=21
  _globals['_MISATGEREBUT']._serialized_end=53
  _globals['_MISATGEENVIAT']._serialized_start=55
  _globals['_MISATGEENVIAT']._serialized_end=88
  _globals['_EMPTY']._serialized_start=90
  _globals['_EMPTY']._serialized_end=97
  _globals['_CHAT']._serialized_start=99
  _globals['_CHAT']._serialized_end=200
# @@protoc_insertion_point(module_scope)
