# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import nameServer_pb2 as nameServer__pb2


class NameServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddClientInfo = channel.unary_unary(
                '/NameServer/AddClientInfo',
                request_serializer=nameServer__pb2.ClientInfo.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetAllClientInfo = channel.unary_unary(
                '/NameServer/GetAllClientInfo',
                request_serializer=nameServer__pb2.Empty.SerializeToString,
                response_deserializer=nameServer__pb2.ClientInfoList.FromString,
                )
        self.GetClientInfoById = channel.unary_unary(
                '/NameServer/GetClientInfoById',
                request_serializer=nameServer__pb2.ClientId.SerializeToString,
                response_deserializer=nameServer__pb2.ClientInfoResponse.FromString,
                )
        self.DeleteClientInfo = channel.unary_unary(
                '/NameServer/DeleteClientInfo',
                request_serializer=nameServer__pb2.ClientId.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class NameServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddClientInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllClientInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClientInfoById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteClientInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NameServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddClientInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.AddClientInfo,
                    request_deserializer=nameServer__pb2.ClientInfo.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetAllClientInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllClientInfo,
                    request_deserializer=nameServer__pb2.Empty.FromString,
                    response_serializer=nameServer__pb2.ClientInfoList.SerializeToString,
            ),
            'GetClientInfoById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClientInfoById,
                    request_deserializer=nameServer__pb2.ClientId.FromString,
                    response_serializer=nameServer__pb2.ClientInfoResponse.SerializeToString,
            ),
            'DeleteClientInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteClientInfo,
                    request_deserializer=nameServer__pb2.ClientId.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'NameServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NameServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddClientInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NameServer/AddClientInfo',
            nameServer__pb2.ClientInfo.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllClientInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NameServer/GetAllClientInfo',
            nameServer__pb2.Empty.SerializeToString,
            nameServer__pb2.ClientInfoList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetClientInfoById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NameServer/GetClientInfoById',
            nameServer__pb2.ClientId.SerializeToString,
            nameServer__pb2.ClientInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteClientInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NameServer/DeleteClientInfo',
            nameServer__pb2.ClientId.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
