# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nameServer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10nameServer.proto\x1a\x1bgoogle/protobuf/empty.proto\"2\n\nClientInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\t\"\x07\n\x05\x45mpty\".\n\x0e\x43lientInfoList\x12\x1c\n\x07\x63lients\x18\x01 \x03(\x0b\x32\x0b.ClientInfo2s\n\nNameServer\x12\x36\n\rAddClientInfo\x12\x0b.ClientInfo\x1a\x16.google.protobuf.Empty\"\x00\x12-\n\x10GetAllClientInfo\x12\x06.Empty\x1a\x0f.ClientInfoList\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nameServer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CLIENTINFO']._serialized_start=49
  _globals['_CLIENTINFO']._serialized_end=99
  _globals['_EMPTY']._serialized_start=101
  _globals['_EMPTY']._serialized_end=108
  _globals['_CLIENTINFOLIST']._serialized_start=110
  _globals['_CLIENTINFOLIST']._serialized_end=156
  _globals['_NAMESERVER']._serialized_start=158
  _globals['_NAMESERVER']._serialized_end=273
# @@protoc_insertion_point(module_scope)
